# Numpy Library

### import Numpy

In [1]:
import numpy as np

### Do Basic Stuff With Numpy:

In [2]:
a = np.array(5)
a

array(5)

In [3]:
# create Array To Range (15)
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
# Reshape "a" to a matrix in Shape 3*5
# 3 Rows, 5 columns
# It Only works for "arange()"
"""
a.reshape(3, 5)
          |  |
     Row <-  -> Columns
"""
a.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
b = np.arange(24)
b = b.reshape(4, 6)

 # See the shape of the matrix
print(f"Shape Of the matrix --> {b.shape}")

# Number Of Dimensions
print(f"Number Of Dimensions --> {b.ndim}")

# See The Size of the matrix
print(f"Size of the matrix --> {b.size}")

# See The Type of the matrix
print(f"Type of the matrix --> {b.dtype}")


Shape Of the matrix --> (4, 6)
Number Of Dimensions --> 2
Size of the matrix --> 24
Type of the matrix --> int64


In [23]:
# Get Zeros and ones
z = np.zeros((2, 3, 6))
print("------ Zeros:")
print(z)

# You Can use Ones
o = np.ones((3, 2, 4))
print("------ Ones:")
print(o)

------ Zeros:
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]
------ Ones:
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### Some Operations:

In [24]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)

In [29]:
c = a * b
c

array([  0,  30,  80, 150])

In [31]:
# Check Grater-than.
c > 50

array([False, False,  True,  True])

In [36]:
# See The Sine of the Matrix
np.sin(c)

array([ 0.        , -0.98803162, -0.99388865, -0.71487643])